### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by sboyls** [nagix/chartjs-plugin-streaming#2]
I get the following gulp build error for the streaming plugin:
gulp build
[22:47:25] Using gulpfile ~/node_modules/chartjs-plugin-streaming/gulpfile.js
[22:47:25] Starting 'build'...
options.entry is deprecated, use options.input
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Unexpected key 'moduleName' found, expected one of: acorn, amd, banner, cache, context, entry, exports, extend, external, file, footer, format, globals, indent, input, interop, intro, legacy, moduleContext, name, noConflict, onwarn, output, outro, paths, plugins, preferConst, pureExternalModules, sourcemap, sourcemapFile, strict, targets, treeshake, watch
    at validateKeys (/home/sboyls/node_modules/chartjs-plugin-streaming/node_modules/rollup/dist/rollup.js:171:11)
    at checkInputOptions (/home/sboyls/node_modules/chartjs-plugin-streaming/node_modules/rollup/dist/rollup.js:10154:14)
    at Object.rollup (/home/sboyls/node_modules/chartjs-plugin-streaming/node_modules/rollup/dist/rollup.js:10225:3)
    at /home/sboyls/node_modules/chartjs-plugin-streaming/node_modules/rollup-stream/index.js:65:19
    at process._tickCallback (internal/process/next_tick.js:109:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:502:3

Help!

**Comment by nagix** [comment]
`rollup.config.js` has been updated to support the latest version of rollup.
